message(STATUS "[TOOLCHAIN] Applying configs: ${CMAKE_CURRENT_LIST_FILE}")

# Internal configs
set(CMAKE_GENERATOR_PLATFORM ? CACHE STRING "" FORCE)
set(CMAKE_UNIX_GENERATOR_PLATFORM ? CACHE STRING "" FORCE)
set(JUG_BUILD_PLATFORM_NAME ? CACHE STRING "" FORCE)
set(JUG_MATCH_INSTALL_ARCH ON CACHE STRING "" FORCE)

# CMake configs
#set(CMAKE_SYSTEM_NAME ?)
#set(CMAKE_SYSTEM_PROCESSOR ?)
#set(CMAKE_LIBRARY_PATH "?")
#set(CMAKE_INCLUDE_PATH "?")
#set(CMAKE_FIND_ROOT_PATH "?")
#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# CTest Configs
#set(CMAKE_TEST_ENVIRONMENT ?)

# C/C++ compiler configs
#set(CMAKE_C_COMPILER ?)
#set(CMAKE_CXX_COMPILER ?)
#set(CMAKE_CROSSCOMPILING_EMULATOR ?)

# C/C++ flags & linker flags
#set(CMAKE_C_FLAGS "?" CACHE STRING "" FORCE)
#set(CMAKE_CXX_FLAGS "?" CACHE STRING "" FORCE)
#set(CMAKE_EXE_LINKER_FLAGS "?" CACHE STRING "" FORCE)
#set(CMAKE_SHARED_LINKER_FLAGS "?" CACHE STRING "" FORCE)
