; Manifest
; Contains all binary versioning information

[TARGET:JuggernyautCompiler]
VERSION="0.0.1-alpha.001"
DESCRIPTION="Juggernyaut Compiler"

[TARGET:JuggernyautBaseLibrary]
VERSION="INHERIT:TARGET:JuggernyautCompiler"
DESCRIPTION="Juggernyaut Base Library"

[TARGET:JuggernyautCommsLibrary]
VERSION="INHERIT:TARGET:JuggernyautCompiler"
DESCRIPTION="Juggernyaut Communications Library"

[TARGET:JuggernyautCommonLibrary]
VERSION="INHERIT:TARGET:JuggernyautCompiler"
DESCRIPTION="Juggernyaut Common Internals Library"

[TARGET:JuggernyautParserLibrary]
VERSION="INHERIT:TARGET:JuggernyautCompiler"
DESCRIPTION="Juggernyaut Common Internals Library"
