; Manifest
; Contains all binary versioning information

[TARGET:JuggernyautCore]
VERSION="ARG:JUG_RELEASE_VERSION"
DESCRIPTION="Juggernyaut Core"

[TARGET:JuggernyautDiagnosticsLibrary]
VERSION="INHERIT:TARGET:JuggernyautCore"
DESCRIPTION="Juggernyaut Core Diagnostics Library"

[TARGET:JuggernyautDataLibrary]
VERSION="INHERIT:TARGET:JuggernyautCore"
DESCRIPTION="Juggernyaut Core Data Library"

[TARGET:JuggernyautParserLibrary]
VERSION="INHERIT:TARGET:JuggernyautCore"
DESCRIPTION="Juggernyaut Core Parser Library"

[TARGET:JuggernyautSessionLibrary]
VERSION="INHERIT:TARGET:JuggernyautCore"
DESCRIPTION="Juggernyaut Core Front-End Session Library"
