; Manifest
; Contains all binary versioning information

[TARGET:JuggernyautCore]
VERSION="ARG:JUG_RELEASE_VERSION"
DESCRIPTION="Juggernyaut Core"

[TARGET:JuggernyautCommonLibrary]
VERSION="INHERIT:TARGET:JuggernyautCore"
DESCRIPTION="Juggernyaut Core Common Internals Library"

[TARGET:JuggernyautDiagnosticsLibrary]
VERSION="INHERIT:TARGET:JuggernyautCore"
DESCRIPTION="Juggernyaut Core Diagnostics Library"

[TARGET:JuggernyautStoreLibrary]
VERSION="INHERIT:TARGET:JuggernyautCore"
DESCRIPTION="Juggernyaut Core 'Code Source' Store Library"

[TARGET:JuggernyautParserLibrary]
VERSION="INHERIT:TARGET:JuggernyautCore"
DESCRIPTION="Juggernyaut Core Parser Library"

[TARGET:JuggernyautSessionLibrary]
VERSION="INHERIT:TARGET:JuggernyautCore"
DESCRIPTION="Juggernyaut Core Front-End Session Library"
