; Manifest
; Contains all binary versioning information

[TARGET:JuggernyautCompiler]
VERSION="ARG:JUG_RELEASE_VERSION"
DESCRIPTION="Juggernyaut Compiler"

[TARGET:JugCompilerBaseLibrary]
VERSION="INHERIT:TARGET:JuggernyautCompiler"
DESCRIPTION="Juggernyaut Compiler Base Library"

[TARGET:JugCompilerConsoleLibrary]
VERSION="INHERIT:TARGET:JuggernyautCompiler"
DESCRIPTION="Juggernyaut Compiler Console Library"

[TARGET:JugCompilerStoreLibrary]
VERSION="INHERIT:TARGET:JuggernyautCompiler"
DESCRIPTION="Juggernyaut Compiler Store Library"
