; Manifest
; Contains all binary versioning information

[TARGET:JugUtility]
VERSION="ARG:JUG_RELEASE_VERSION"
DESCRIPTION="Juggernyaut Utility"

[TARGET:JuggernyautCommonLibrary]
VERSION="INHERIT:TARGET:JugUtility"
DESCRIPTION="Juggernyaut Common Library"
