on:
  workflow_call: # Added this line to make it reusable
    inputs:
      mac_system:
        required: false
        type: string
        default: macos-latest
      build_platform:
        required: true
        type: string
      build_platform_name:
        required: true
        type: string
      build_mode:
        required: true
        type: string
      bundle_binaries:
        required: true
        type: boolean
      release_version:
        required: false
        type: string
        default: 0.0.0-github_mac.000

jobs:

  # macOS
  build-binaries-on-macos:
    name: macOS ${{inputs.build_platform_name}}
    runs-on: ${{inputs.mac_system}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup CMake 4.2+
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.2.x'

    - name: Set up JDK 23
      uses: actions/setup-java@v5
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        brew install --formula cmake --quiet

    - name: Make the ".build" directory
      run: mkdir ${{github.workspace}}/.build

    - name: Configure CMake
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=${{inputs.build_mode}} -JUG_GENERATOR_PLATFORM=${{inputs.build_platform}} \
          -DJUG_CLEANUP=ON -DJUG_RELEASE_VERSION="${{inputs.release_version}}"
      working-directory: .build

    - name: Build
      run: cmake --build . --config ${{inputs.build_mode}} --parallel 3 --verbose
      working-directory: .build

    # TO-DO: ADD TESTS!

    - name: Extract version (optional)
      if: inputs.bundle_binaries
      run: |
        set -e
        VERSION=$(${{github.workspace}}/.dist/${{inputs.build_mode}}/${{inputs.build_platform_name}}/bin/jug --version \
          | head -n 1)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Upload Binaries Artifact (optional)
      if: inputs.bundle_binaries
      uses: actions/upload-artifact@v7
      with:
        name: Juggernyaut-${{inputs.build_mode}}-v${{env.VERSION}}-macOS-${{inputs.build_platform_name}}
        path: ${{github.workspace}}/.dist/${{inputs.build_mode}}/${{inputs.build_platform_name}}/

    # Used to display all patch errors (I ain't got no money for a macOS, deal with it)
    #- name: Debug patch rejects
    #  if: always()
    #  run: find . -type f -regex ".*\.rej$" -print0 | xargs -0 cat
    #  working-directory: .build
