name: Binaries
on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:

  # Debug
  build-binaries-debug:
    name: Debug
    uses: ./.github/workflows/_binaries_dynamic_build.yml
    with:
      build_mode: Debug
      bundle_binaries: false
      full_build:
        ${{(github.event_name == 'push' && endsWith(github.event.head_commit.message, ' -FULL')) ||
        github.event_name == 'pull_request'}}
      security_analysis: false

  # Release
  build-binaries-release:
    name: Release
    uses: ./.github/workflows/_binaries_dynamic_build.yml
    if: ${{(github.event_name == 'push' && endsWith(github.event.head_commit.message, ' -REL')) || github.event_name == 'pull_request'}}
    needs:
      - build-binaries-debug
    with:
      build_mode: Release
      bundle_binaries: false
      full_build:
        ${{(github.event_name == 'push' && endsWith(github.event.head_commit.message, ' -FULL')) ||
        github.event_name == 'pull_request'}}
      security_analysis:
        ${{(github.event_name == 'push' && endsWith(github.event.head_commit.message, ' -SEC')) ||
        github.event_name == 'pull_request'}}
