name: VSCode Extension
on:
  push:
    branches: 
    - "main"
  pull_request:
    branches: 
    - "main"
  workflow_call: # Added this line to make it reusable
    # Add inputs here if needed. Example:
    inputs:
      upload_artifact:
        required: false
        type: boolean
        default: false

jobs:

  # Windows
  build-vscode-extension-on-windows-latest:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install NodeJS dependencies
      run: npm i
      working-directory: ${{github.workspace}}/extensions/VSCode

    - name: Package the VSCode Extension
      run: npm run win-package
      working-directory: ${{github.workspace}}/extensions/VSCode

    - name: Get VSCode Extension version
      id: get-file
      run: |
        $Files = Get-ChildItem -Path "./" -Filter "*.vsix"
        $Count = 0
        if ($Files.Count -eq 2) {
          foreach ($File in $Files) {
            $FileName = $File.Name
            $VersionWithExt = $FileName.Replace("juggernyaut-", "")
            $NewFileName = "Juggernyaut-VSCode-v$VersionWithExt"
            Rename-Item -Path $File.FullName -NewName $NewFileName
            $Count++
            echo "VSCODE_EXT_FILE_NAME_$Count=$NewFileName" >> $env:GITHUB_ENV
          }
        } else {
          Write-Error "Found $Files.Count .vsix files in ${{github.workspace}}/extensions/VSCode/"
        }
      working-directory: ${{github.workspace}}/extensions/VSCode

    - name: Upload Artifact \#1 (optional)
      if: inputs.upload_artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.VSCODE_EXT_FILE_NAME_1}}
        path: ${{github.workspace}}/extensions/VSCode/${{env.VSCODE_EXT_FILE_NAME_1}}

    - name: Upload Artifact \#2 (optional)
      if: inputs.upload_artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.VSCODE_EXT_FILE_NAME_2}}
        path: ${{github.workspace}}/extensions/VSCode/${{env.VSCODE_EXT_FILE_NAME_2}}
